name: Deploy to Production

on:
  push:
    branches:
      - main # Ou a branch que você usa para deploy, por exemplo, master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy with rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.DEPLOY_PATH }}

      - name: Run post-deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/htdocs/srv891877.hstgr.cloud
            # php artisan optimize:clear
            # php artisan config:cache
            # php artisan route:cache
            # php artisan view:cache
            # php artisan event:cache
            # composer dump-autoload
            # php artisan cache:clear
            # php artisan queue:restart
            # php artisan up
