name: Deploy via Git Pull

on:
  push:
    branches:
      - main # Dispara o deploy quando há um push para a branch 'main'
  
  workflow_dispatch: # Permite execução manual a partir da aba "Actions"

jobs:
  deploy:
    runs-on: ubuntu-latest # O ambiente de execução para o workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Execute Git Pull and Post-Deployment Commands
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd /home/user/htdocs/srv891877.hstgr.cloud

          echo "Executando git pull..."
          git pull origin main

          echo "Executando composer install no servidor..."
          composer install --no-dev --optimize-autoloader
          
          echo "Limpando caches do Laravel..."
          php artisan optimize:clear # Limpa todos os caches
          php artisan config:cache   # Recria o cache de configuração
          php artisan route:cache    # Recria o cache de rotas
          php artisan view:cache     # Recria o cache de views

          # Comandos de reinício de serviços (COMENTADOS TEMPORARIAMENTE)
          # echo "Reiniciando PHP-FPM e Nginx/Apache..."
          # sudo systemctl reload php8.3-fpm # AJUSTE A VERSÃO DO PHP AQUI
          # sudo systemctl restart nginx    # OU sudo systemctl restart apache2

          echo "Deploy concluído com sucesso!"
        EOF
